/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ai.projekat.organizacija.form.tim;

import rs.ac.bg.fon.ai.projekat.organizacija.controller.KlijentController;
import rs.ac.bg.fon.ai.projekat.organizacija.domain.Tim;
import rs.ac.bg.fon.ai.projekat.organizacija.models.ModelTabeleTim;
import rs.ac.bg.fon.ai.projekat.organizacija.pomocne.Moodovi;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;




/**
 *
 * @author Ivana
 */
public class PretragaTima extends javax.swing.JDialog {
 ModelTabeleTim model;
    /**
     * Creates new form PretragaTima
     */
    public PretragaTima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        model = new ModelTabeleTim();
        Thread th = new Thread(model);
        th.start();
        tblTimovi.setModel(model);
        setTitle("Pretraga tima");
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivTima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimovi = new javax.swing.JTable();
        btnDetaljiTima = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga(naziv tima) :");

        txtNazivTima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivTimaKeyReleased(evt);
            }
        });

        tblTimovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTimovi);

        btnDetaljiTima.setText("DETALJI TIMA");
        btnDetaljiTima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiTimaActionPerformed(evt);
            }
        });

        jButton1.setText("OSVEZI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetaljiTima)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNazivTima, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetaljiTima)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivTimaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivTimaKeyReleased
       String param = txtNazivTima.getText();
       if(param.matches("\\d+")){
           
           JOptionPane.showMessageDialog(this," Nije dobar format unosa,naziv nema brojeve");
           return;
       }
       ModelTabeleTim mt=((ModelTabeleTim) tblTimovi.getModel());
       mt.setParametar(param);
       
    }//GEN-LAST:event_txtNazivTimaKeyReleased

    private void btnDetaljiTimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiTimaActionPerformed
       int row = tblTimovi.getSelectedRow();

        if (row != -1) {
            Tim t = ((ModelTabeleTim) tblTimovi.getModel()).vratiOdabraniTim(row);
           try {
               Tim ucitanIzBaze=KlijentController.getInstance().ucitajTim(t);
               SwingUtilities.invokeLater(new Runnable() {
                  public void run() {
                    try {
                       new DetaljiTima(PretragaTima.this,null, true, ucitanIzBaze,Moodovi.PRIKAZ).setVisible(true);
                    } catch (Exception ex) {
                        Logger.getLogger(PretragaTima.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
               }); 
                SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            JOptionPane.showMessageDialog(null, "Sistem je ucitao tim", "GRESKA", JOptionPane.INFORMATION_MESSAGE);
        }
    });
               
               
           } catch (Exception ex) {
               Logger.getLogger(PretragaTima.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        else{
             JOptionPane.showMessageDialog(null, "Sistem ne moze da ucita tim", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetaljiTimaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModelTabeleTim model = new ModelTabeleTim();
        Thread th = new Thread(model);
        th.start();
        tblTimovi.setModel(model);
        txtNazivTima.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljiTima;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTimovi;
    private javax.swing.JTextField txtNazivTima;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
       ModelTabeleTim mt=(ModelTabeleTim) tblTimovi.getModel();
       mt.refreshTable();
    }

   
}
