/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package  rs.ac.bg.fon.ai.projekat.organizacija.form.zadatak;

import java.io.IOException;
import rs.ac.bg.fon.ai.projekat.organizacija.controller.KlijentController;
import rs.ac.bg.fon.ai.projekat.organizacija.domain.Zadatak;
import rs.ac.bg.fon.ai.projekat.organizacija.form.clan.PretraziClana;
import rs.ac.bg.fon.ai.projekat.organizacija.form.tim.PretragaTima;
import rs.ac.bg.fon.ai.projekat.organizacija.form.zadatak.DetaljiZadatka;
import rs.ac.bg.fon.ai.projekat.organizacija.models.ModelTabeleZadatak;
import rs.ac.bg.fon.ai.projekat.organizacija.pomocne.Moodovi;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;



/**
 *
 * @author Ivana
 */
public class PretraziZadatak extends javax.swing.JDialog {

    /**
     * Creates new form PretraziZadatak
     */
    public PretraziZadatak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga zadatka");
        try {
            ModelTabeleZadatak model = new ModelTabeleZadatak();
            Thread th = new Thread(model);
            th.start();
            tblZadaci.setModel(model);

        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZadaci = new javax.swing.JTable();
        txtNazivZadatka = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga(naziv zadatka)");

        tblZadaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZadaci);

        txtNazivZadatka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivZadatkaKeyReleased(evt);
            }
        });

        jButton1.setText("DETALJI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OSVEZI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtNazivZadatka))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivZadatkaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivZadatkaKeyReleased
        String param = txtNazivZadatka.getText();

        if (param.matches("\\d+")) {

            JOptionPane.showMessageDialog(this, " Nije dobar format unosa,naziv nema brojeve");
            return;
        }
        ModelTabeleZadatak mt = (ModelTabeleZadatak) tblZadaci.getModel();

        mt.setParametar(param);


    }//GEN-LAST:event_txtNazivZadatkaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = tblZadaci.getSelectedRow();

        if (row != -1) {

            Zadatak z = ((ModelTabeleZadatak) tblZadaci.getModel()).vratiOdabraniZadatak(row);

             try {
              Zadatak ucitanIzBaze=KlijentController.getInstance().ucitajZadatak(z);
               SwingUtilities.invokeLater(new Runnable() {
                  public void run() {
                    try {
                       new DetaljiZadatka(PretraziZadatak.this,null, true, ucitanIzBaze,Moodovi.PRIKAZ).setVisible(true);
                    } catch (Exception ex) {
                        java.util.logging.Logger.getLogger(PretraziClana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
    }
               }); 
                SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            JOptionPane.showMessageDialog(null, "Sistem je ucitao zadatak", "POTVRDA", JOptionPane.INFORMATION_MESSAGE);
        }
    });
               
               
           } catch (Exception ex) {
               java.util.logging.Logger.getLogger(PretragaTima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           }
        }
        else{
             JOptionPane.showMessageDialog(null, "Sistem ne moze da ucita zadatak", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ModelTabeleZadatak model = new ModelTabeleZadatak();
        Thread th = new Thread(model);
        th.start();
        tblZadaci.setModel(model);
        txtNazivZadatka.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZadaci;
    private javax.swing.JTextField txtNazivZadatka;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        ModelTabeleZadatak mt = (ModelTabeleZadatak) tblZadaci.getModel();
        mt.refreshTable();
    }
}
