/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ai.projekat.organizacija.form.projekat;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializer;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import rs.ac.bg.fon.ai.projekat.organizacija.controller.KlijentController;
import rs.ac.bg.fon.ai.projekat.organizacija.domain.Projekat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.projekat.organizacija.domain.Clan;

/**
 *
 * @author Ivana
 */
public class KreirajProjekat extends javax.swing.JDialog {

    /**
     * Creates new form KreirajProjekat
     */
    public KreirajProjekat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Kreiranje projekta");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNazivProjekta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVrstaProjekta = new javax.swing.JTextField();
        txtDatumPocetka = new javax.swing.JTextField();
        txtDatumZavrsetka = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("KREIRAJ PROJEKAT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv projekta");

        jLabel2.setText("Vrsta projekta");

        jLabel3.setText("Datum pocetka");

        jLabel4.setText("Datum zavrsetka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDatumPocetka)
                    .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txtVrstaProjekta)
                    .addComponent(txtNazivProjekta))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVrstaProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nazivProjekta = txtNazivProjekta.getText();
        String vrstaProjekta = txtVrstaProjekta.getText();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String dateString1 = txtDatumPocetka.getText();
        String dateString2 = txtDatumZavrsetka.getText();
        System.out.println(dateString1);
        System.out.println(dateString2);

        LocalDate datumPocetka;
        LocalDate datumZavrsetka;
        

        try {
            datumPocetka = LocalDate.parse(dateString1, formatter);
            datumZavrsetka = LocalDate.parse(dateString2, formatter);
            String formatDatuma = DaLiSuDatumiIspravni(datumPocetka, datumZavrsetka);
            if (!formatDatuma.equals("")) {
                JOptionPane.showMessageDialog(this, formatDatuma, "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Projekat p = new Projekat(0, nazivProjekta, vrstaProjekta, datumPocetka, datumZavrsetka);

            p = KlijentController.getInstance().dodajProjekat(p);
            upisiUJSON(p);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niste uneli datum u ispravnom formatu! Ispravan format:yyyy-MM-dd");

        }
        JOptionPane.showMessageDialog(this, "Sistem je kreirao projekat.", "Informacija", JOptionPane.INFORMATION_MESSAGE);
        osveziFormu();


    }//GEN-LAST:event_jButton1ActionPerformed

    private String DaLiSuDatumiIspravni(LocalDate datumDodele, LocalDate krajnjiRok) {
        String poruka = "";
        if (datumDodele.isAfter(krajnjiRok)) {
            poruka += "Datum dodele mora biti pre datuma krajnjeg roka \n";

        }
        if (krajnjiRok.isBefore(LocalDate.now())) {
            poruka += "Krajnji rok ne moze biti u proslosti \n";
        }
        return poruka;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDatumPocetka;
    private javax.swing.JTextField txtDatumZavrsetka;
    private javax.swing.JTextField txtNazivProjekta;
    private javax.swing.JTextField txtVrstaProjekta;
    // End of variables declaration//GEN-END:variables

    private void osveziFormu() {
        txtNazivProjekta.setText("");
        txtVrstaProjekta.setText("");
        txtDatumPocetka.setText("");
        txtDatumZavrsetka.setText("");

    }

    private void upisiUJSON(Projekat p) {
       String filePath = "projekat.json";

        GsonBuilder gsonBuilder = new GsonBuilder();
        gsonBuilder.setPrettyPrinting();

        gsonBuilder.registerTypeAdapter(LocalDate.class, (JsonSerializer<LocalDate>) (src, typeOfSrc, context) -> 
            new com.google.gson.JsonPrimitive(src.toString())
        );
        gsonBuilder.registerTypeAdapter(LocalDate.class, (JsonDeserializer<LocalDate>) (json, typeOfT, context) -> 
            LocalDate.parse(json.getAsString())
        );

        Gson gson = gsonBuilder.create();

        try (FileWriter out = new FileWriter(filePath)) {
            String jsonString = gson.toJson(p);
            System.out.println("JSON string: " + jsonString);
            out.write(jsonString);
            System.out.println("Uspešno upisano u fajl: " + filePath);
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Greška pri pisanju u fajl: " + filePath);
        }
    }
 
        
    
}
        
    



